[package]
name = "warp-runner"
version = "0.3.0"
authors = ["Diego Giagio <diego@giagio.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0"
memmem = "0.1.1"
flate2 = "1.0"
tar = "0.4"
dirs = "4.0"
log = "0.4.5"
remove_dir_all = "0.7"
simple_logger = "1.0.1"
