[package]
name = "warp-packer"
version = "0.4.0"
authors = ["Diego Giagio <diego@giagio.com>"]
edition = "2021"

[dependencies]
clap = "2.32.0"
tempdir = "0.3.7"
flate2 = "1.0"
tar = "0.4"
lazy_static = "1.1.0"
